#DEV environment
server:
  port: 3000

app:
  message: This is the property file fo the ${spring.application.name} specific to DEV1 Environment

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: admin
    password: admin